reduce Lambda asset size (#74)
* use uv for dependency management

* run cdk synth in CI to check asset package size

* update minimum python version to 3.9

* strip debug symbols from compiled C/C++ code in Lambda docker build

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -29,40 +29,44 @@ jobs:
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        python-version: ['3.8', '3.9', '3.10']
+        python-version: ['3.10', '3.11', '3.12', '3.13']
 
     steps:
-      - uses: actions/checkout@v3
-      - name: Set up Python ${{ matrix.python-version }}
-        uses: actions/setup-python@v4
-        with:
-          python-version: ${{ matrix.python-version }}
+      - uses: actions/checkout@v4
 
+      - name: Install uv
+        uses: astral-sh/setup-uv@v3
+        with:
+          version: "0.5.*" 
+          enable-cache: true
+    
+      - name: Set up Python ${{ matrix.python-version }}
+        run: uv python install ${{ matrix.python-version }}
+      
       - name: Install dependencies
         run: |
-          python -m pip install --upgrade pip
-          python -m pip install -e .["test"]
+          uv sync --all-extras
 
       - name: run pre-commit
         if: ${{ matrix.python-version == env.LATEST_PY_VERSION }}
         run: |
-          python -m pip install pre-commit
-          pre-commit run --all-files
+          uv run pre-commit run --all-files
 
       - name: Run tests
-        run: python -m pytest --cov titiler.xarray --cov-report term-missing -s -vv
+        run: uv run pytest
 
   deploy:
     needs: [tests]
     runs-on: ubuntu-latest
-    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' || startsWith(github.ref, 'refs/tags/v')
+    env:
+      UV_PYTHON: 3.12
   
     defaults:
       run:
         working-directory: infrastructure/aws
 
     steps:
-      - uses: actions/checkout@v3
+      - uses: actions/checkout@v4
 
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v2
@@ -76,23 +80,39 @@ jobs:
         with:
           node-version: 18
 
-      - name: Install cdk
-        run: npm install -g aws-cdk
-
-      - name: Set up Python
-        uses: actions/setup-python@v4
+      - name: Install uv
+        uses: astral-sh/setup-uv@v3
         with:
-          python-version: '3.x'
+          version: "0.5.*" 
+          enable-cache: true
 
       - name: Install dependencies
         run: |
-          python -m pip install --upgrade pip
-          python -m pip install -r requirements-cdk.txt
+          uv sync --only-group deployment
+          uv run npm install
 
+      - name: CDK Synth
+        run: uv run --only-group deployment npm run cdk -- synth
+
+      - name: Check Asset Sizes
+        run: |
+          MAX_SIZE_BYTES=262144000  # 262 MB in bytes
+          for dir in cdk.out/asset.*; do
+            if [ -d "$dir" ]; then
+              size=$(du -sb "$dir" | cut -f1)
+              if [ "$size" -gt $MAX_SIZE_BYTES ]; then
+                echo "Directory $dir exceeds 262 MB with size $size bytes (max: $MAX_SIZE_BYTES bytes)."
+                exit 1 # Exit with failure if any asset directory is too large
+              fi
+              echo "Asset directory $dir size: $size bytes"
+            fi
+          done
+          echo "All asset directories are within size limits."
+      
       # Build and deploy to the development environment whenever there is a push to main or dev
       - name: Build & Deploy Development
         if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'
-        run: npm run cdk -- deploy titiler-xarray-development --require-approval never
+        run: uv run npm run cdk -- deploy titiler-xarray-development --require-approval never
         env:
           TITILER_XARRAY_PYTHONWARNINGS: ignore
           TITILER_XARRAY_DEBUG: True
@@ -102,7 +122,7 @@ jobs:
       # Build and deploy to production deployment whenever there a new tag is pushed
       - name: Build & Deploy Production
         if: startsWith(github.ref, 'refs/tags/v')
-        run: npm run cdk -- deploy titiler-xarray-production --require-approval never
+        run: uv run npm run cdk -- deploy titiler-xarray-production --require-approval never
         env:
           TITILER_XARRAY_PYTHONWARNINGS: ignore
           TITILER_XARRAY_DEBUG: True
